/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Convertor;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMONS
 */
public class Length extends javax.swing.JFrame {

    /**
     * Creates new form Length
     */
    public Length() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstLength = new javax.swing.JComboBox<>();
        secondLength = new javax.swing.JComboBox<>();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Length converter");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 20, 420, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FROM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 110, 70, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(770, 110, 70, 30);

        firstLength.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose one", "mile", "meter", "feet", "kilometer" }));
        jPanel1.add(firstLength);
        firstLength.setBounds(420, 140, 180, 40);

        secondLength.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose one", "mile", "meter", "feet", "kilometer" }));
        jPanel1.add(secondLength);
        secondLength.setBounds(760, 140, 160, 40);

        t5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        jPanel1.add(t5);
        t5.setBounds(420, 200, 160, 40);

        t6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(t6);
        t6.setBounds(760, 200, 160, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 290, 160, 40);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 290, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(780, 290, 120, 40);

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(590, 370, 190, 50);

        show_validation_here.setForeground(new java.awt.Color(255, 0, 51));
        show_validation_here.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                show_validation_hereKeyPressed(evt);
            }
        });
        jPanel1.add(show_validation_here);
        show_validation_here.setBounds(420, 240, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       BUtton home = new BUtton();
         home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        firstLength.setSelectedIndex(0);
        secondLength.setSelectedIndex(0);
        t5.setText(null);
        t6.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double km = Double.parseDouble(t5.getText());
        double f = Double.parseDouble(t5.getText());
        double mil = Double.parseDouble(t5.getText());
        double m = Double.parseDouble(t5.getText());
        String box1=(String)firstLength.getSelectedItem();
        String box2=(String)secondLength.getSelectedItem();
        if((t5.getText().equals(""))||(box1.equals("choose one"))||(box2.equals("choose one"))){
            JOptionPane.showMessageDialog(null,"you must enter a value to copute",
                    "DST System",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(box1.equals("kilometer") && box2.equals("mile")){
                double mile = km * 0.621;
                t6.setText(String.valueOf(mile));
            }
        else if(box1.equals("kilometer") && box2.equals("kilometer")){
                double kl = km;
                t6.setText(String.valueOf(kl));
            }
        else if(box1.equals("kilometer") && box2.equals("meter")){
                double meter = km * 1000;
                t6.setText(String.valueOf(meter));
            }
        else if(box1.equals("kilometer") && box2.equals("feet")) {
                double feet = km * 3280.84;
                t6.setText(String.valueOf(feet));
            }
        else if(box1.equals("mile") && box2.equals("kilometer")) {
                double kilometer = mil * 1.60934;
                t6.setText(String.valueOf(kilometer));
            }
        else if(box1.equals("mile") && box2.equals("mle")) {
                double ml = mil;
                t6.setText(String.valueOf(ml));
            }
        else if(box1.equals("mile") && box2.equals("meter")) {
                double meter = mil * 1609.34;
                t6.setText("" + meter);
            }
        else if(box1.equals("mile") && box2.equals("feet")) {
                double feet = mil * 5280;
                t6.setText(String.valueOf(feet));
            }
        else if(box1.equals("feet") && box2.equals("kilometer")) {
                double kilometer = f * 0.0003048;
                t6.setText(String.valueOf( kilometer));
            }
        else if(box1.equals("feet") && box2.equals("feet")) {
                double ft = f;
                t6.setText(String.valueOf(ft));
            }
        else if(box1.equals("feet") && box2.equals("meter")) {
                double meter = f * 0.3048;
                t6.setText(String.valueOf(meter));
            }
        else if (box1.equals("feet") && box2.equals("mile")){
                double mile = f * 0.000189394;
                t6.setText(String.valueOf(mile));
            }
        else if(box1.equals("meter") && box2.equals("kilometer")) {
                double kilometer = m * 0.001;
                t6.setText(String.valueOf(kilometer));
            }
        else if(box1.equals("meter") && box2.equals("feet")) {
                double feet = m * 3.28084;
                t6.setText(String.valueOf(feet));
            }
        else if (box1.equals("meter") && box2.equals("mile")){
                 double mile = m * 0.000621371;
                t6.setText(String.valueOf(mile));
            }
        else if (box1.equals("meter") && box2.equals("meter")){
                 double mt = m;
                t6.setText(String.valueOf(mt));
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void show_validation_hereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_show_validation_hereKeyPressed
       
    }//GEN-LAST:event_show_validation_hereKeyPressed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
         try{
            int i=Integer.parseInt(t6.getText());
            show_validation_here.setText("");
        }
        catch(NumberFormatException e){
            show_validation_here.setText("Please write Digits");
        }
    }//GEN-LAST:event_t5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Length().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> firstLength;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondLength;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
