/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Convertor;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMONS
 */
public class Mass extends javax.swing.JFrame {

    /**
     * Creates new form Mass
     */
    public Mass() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstMass = new javax.swing.JComboBox<>();
        secondMass = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.desktop);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mass Converter");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 40, 340, 50);

        firstMass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstMass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "kilogram", "milligram", "pound", "ounce", "tone" }));
        jPanel1.add(firstMass);
        firstMass.setBounds(360, 170, 150, 40);

        secondMass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondMass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "kilogram", "milligram", "pound", "ounce", "tone" }));
        jPanel1.add(secondMass);
        secondMass.setBounds(690, 170, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("FROM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 130, 53, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(690, 130, 70, 22);

        t7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });
        jPanel1.add(t7);
        t7.setBounds(360, 230, 250, 50);

        t8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(690, 230, 240, 50);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 350, 150, 50);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 350, 160, 50);

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(770, 350, 130, 50);

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(560, 430, 185, 70);

        show_validation_here.setForeground(new java.awt.Color(255, 0, 0));
        show_validation_here.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                show_validation_hereKeyPressed(evt);
            }
        });
        jPanel1.add(show_validation_here);
        show_validation_here.setBounds(370, 290, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          firstMass.setSelectedIndex(0);
        secondMass.setSelectedIndex(0);
        t7.setText(null);
        t8.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         BUtton home = new BUtton();
         home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double kg = Double.parseDouble(t7.getText());
        double mg = Double.parseDouble(t7.getText());
        double o = Double.parseDouble(t7.getText());
        double p = Double.parseDouble(t7.getText());
        double t = Double.parseDouble(t7.getText());
        String box1=(String)firstMass.getSelectedItem();
        String box2=(String)secondMass.getSelectedItem();
        if((t7.getText().equals(""))||(box1.equals("Choose one"))||(box2.equals("Choose one"))){
            JOptionPane.showMessageDialog(null,"you must enter a value to compute","DST system",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else if(box1.equals("kilogram") && box2.equals("kilogram")){
                double k = kg ;
                t8.setText(String.valueOf(k));
            }
        else if(box1.equals("kilogram") && box2.equals("milligram")){
                double k = kg*1000000 ;
               String value = String.format("%.2f",k);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("kilogram") && box2.equals("pound")){
                double k = kg*2.205 ;
               String value = String.format("%.2f",k);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("kilogram") && box2.equals("ounce")){
                double k = kg* 35.274 ;
                String value = String.format("%.2f",k);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("kilogram") && box2.equals("tone")){
                double k = kg/1000 ;
               String value = String.format("%.2f",k);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("milligram") && box2.equals("milligram")){
                double m = mg ;
               String value = String.format("%.2f",m);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("milligram") && box2.equals("kilogram")){
                double m = mg/1000000 ;
                String value = String.format("%.2f",m);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("milligram") && box2.equals("pound")){
                double m = mg/453592 ;
                String value = String.format("%.2f",m);
                t8.setText(String.valueOf(value));
            }
         else if(box1.equals("milligram") && box2.equals("ounce")){
                double m = mg/ 28350;
              String value = String.format("%.2f",m);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("milligram") && box2.equals("tone")){
                double m = mg/1000000000 ;
              String value = String.format("%.2f",m);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("pound") && box2.equals("pound")){
                double pon = p ;
                String value = String.format("%.2f",pon);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("pound") && box2.equals("kilogram")){
                double pon = p/2.205 ;
                String value = String.format("%.2f",pon);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("pound") && box2.equals("milligram")){
                double pon = p* 453592 ;
             String value = String.format("%.2f",pon);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("pound") && box2.equals("ounce")){
                double pon = p*16 ;
               String value = String.format("%.2f",pon);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("pound") && box2.equals("tone")){
                double pon = p/ 2205 ;
               String value = String.format("%.2f",pon);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("ounce") && box2.equals("ounce")){
                double on = o ;
               String value = String.format("%.2f",on);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("ounce") && box2.equals("kilogram")){
                double on = o/35.274 ;
                String value = String.format("%.2f",on);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("ounce") && box2.equals("milligram")){
                double on = o*28350 ;
                  String value = String.format("%.2f",on);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("ounce") && box2.equals("pound")){
                double on = o/16 ;
                 String value = String.format("%.2f",on);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("ounce") && box2.equals("tone")){
                double on = o/ 35274;
                 String value = String.format("%.2f",on);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("tone") && box2.equals("tone")){
                double tn = t;
                 String value = String.format("%.2f",tn);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("tone") && box2.equals("kilogram")){
                double tn = t* 1000;
                 String value = String.format("%.2f",tn);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("tone") && box2.equals("milligram")){
                double tn = t* 1000000000;
                 String value = String.format("%.2f",tn);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("tone") && box2.equals("pound")){
                double tn = t*2205;
                 String value = String.format("%.2f",tn);
                t8.setText(String.valueOf(value));
            }
        else if(box1.equals("tone") && box2.equals("ounce")){
                double tn = t* 35274;
                 String value = String.format("%.2f",tn);
                t8.setText(String.valueOf(value));
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void show_validation_hereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_show_validation_hereKeyPressed
       
    }//GEN-LAST:event_show_validation_hereKeyPressed

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
         try{
            int i=Integer.parseInt(t7.getText());
            show_validation_here.setText("");
        }
        catch(NumberFormatException e){
            show_validation_here.setText("Please write Digits");
        }
    }//GEN-LAST:event_t7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> firstMass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondMass;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
