/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Convertor;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMONS
 */
public class Time extends javax.swing.JFrame {

    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        firstTime = new javax.swing.JComboBox<>();
        secondTime = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.desktop);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time Conversion");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 30, 380, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("FROM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 100, 70, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(810, 100, 30, 22);

        t9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t9KeyPressed(evt);
            }
        });
        jPanel1.add(t9);
        t9.setBounds(350, 200, 190, 50);

        t10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(t10);
        t10.setBounds(750, 200, 210, 50);

        firstTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Hours", "Minutes", "Seconds", "Days", "Weeks" }));
        firstTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstTimeActionPerformed(evt);
            }
        });
        jPanel1.add(firstTime);
        firstTime.setBounds(380, 140, 140, 40);

        secondTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Hours", "Minutes", "Seconds", "Days", "Weeks" }));
        jPanel1.add(secondTime);
        secondTime.setBounds(790, 140, 140, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 300, 150, 50);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 300, 130, 50);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(790, 300, 120, 50);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 380, 160, 50);

        show_validation_here.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        show_validation_here.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(show_validation_here);
        show_validation_here.setBounds(350, 250, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         firstTime.setSelectedIndex(0);
        secondTime.setSelectedIndex(0);
        t9.setText(null);
        t10.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BUtton home = new BUtton();
         home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double h = Double.parseDouble(t9.getText());
        double m = Double.parseDouble(t9.getText());
        double s = Double.parseDouble(t9.getText());
        double d = Double.parseDouble(t9.getText());
        double w = Double.parseDouble(t9.getText());
        String box1=(String)firstTime.getSelectedItem();
        String box2=(String)secondTime.getSelectedItem();
        if((t9.getText().equals(""))||(box1.equals("Choose one"))||(box2.equals("Choose one"))){
            JOptionPane.showMessageDialog(null,"you must enter a value to compute",
                    "DST System",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(box1.equals("Hours") && box2.equals("Hours")){
                double hr = h ;
                  String value = String.format("%.2f",hr);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Hours") && box2.equals("Minutes")){
                double hr = h* 60;
                  String value = String.format("%.2f",hr);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Hours") && box2.equals("Seconds")){
                double hr = h* 3600;
                  String value = String.format("%.2f",hr);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Hours") && box2.equals("Days")){
                double hr = h/24 ;
                 String value = String.format("%.2f",hr);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Hours") && box2.equals("Weeks")){
                double hr = h/168;
                 String value = String.format("%.2f",hr);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Minutes") && box2.equals("Minutes")){
                double mn = m;
                t10.setText(String.valueOf(mn));
            }
        else if(box1.equals("Minutes") && box2.equals("Hours")){
                double mn = m/60;
                String value = String.format("%.2f",mn);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Minutes") && box2.equals("Seconds")){
                double mn = m*60;
                 String value = String.format("%.2f",mn);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Minutes") && box2.equals("Days")){
                double mn = m/1440;
                String value = String.format("%.2f",mn);
                t10.setText(String.valueOf(value));
               
            }
        else if(box1.equals("Minutes") && box2.equals("Weeks")){
                double mn = m/10080;
                 String value = String.format("%.2f",mn);
                t10.setText(String.valueOf(value));
                
            }
         else if(box1.equals("Seconds") && box2.equals("Seconds")){
                double sc = s;
                 String value = String.format("%.2f",sc);
                t10.setText(String.valueOf(value));
               
            }
        else if(box1.equals("Seconds") && box2.equals("Minutes")){
                double sc = s/60;
                 String value = String.format("%.2f",sc);
                t10.setText(String.valueOf(value));
                
            }
        else if(box1.equals("Seconds") && box2.equals("Hours")){
                double sc = s/ 3600;
                String value = String.format("%.2f",sc);
                t10.setText(String.valueOf(value));
                
            }
        else if(box1.equals("Seconds") && box2.equals("Days")){
                double sc = s/86400;
                 String value = String.format("%.2f",sc);
                t10.setText(String.valueOf(value));
                
            }
        else if(box1.equals("Seconds") && box2.equals("Weeks")){
                double sc = s/604800;
                 String value = String.format("%.2f",sc);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Days") && box2.equals("Days")){
                double dy= d;
                 String value = String.format("%.2f",dy);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Days") && box2.equals("Hours")){
                double dy= d*24;
                String value = String.format("%.2f",dy);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Days") && box2.equals("Seconds")){
                double dy= d*86400;
                String value = String.format("%.4f",dy);
                t10.setText(String.valueOf(value));
                
            }
        else if(box1.equals("Days") && box2.equals("Weeks")){
                double dy= d/ 7;
                String value = String.format("%.3f",dy);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Days") && box2.equals("Minutes")){
                double dy= d*1440;
                String value = String.format("%.3f",dy);
                t10.setText(String.valueOf(value));
            }
        else if(box1.equals("Weeks") && box2.equals("Weeks")){
                double wk= w;
                String value = String.format("%.3f",wk);
                t10.setText(String.valueOf(value));
            }
         else if(box1.equals("Weeks") && box2.equals("Hours")){
                double wk= w*168;
                String value = String.format("%.3f",wk);
                t10.setText(String.valueOf(value));
            }
         else if(box1.equals("Weeks") && box2.equals("Minutes")){
                double wk= w*10080;
                String value = String.format("%.2f",wk);
                t10.setText(String.valueOf(value));
            }
         else if(box1.equals("Weeks") && box2.equals("Seconds")){
                double wk= w*604800;
                String value = String.format("%.2f",wk);
                t10.setText(String.valueOf(value));
            }
         else if(box1.equals("Weeks") && box2.equals("Days")){
                double wk= w* 7;
                String value = String.format("%.2f",wk);
                t10.setText(String.valueOf(value));
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        
    }//GEN-LAST:event_t9ActionPerformed

    private void t9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyPressed
        try{
            int i=Integer.parseInt(t9.getText());
            show_validation_here.setText("");
        }
        catch(NumberFormatException e){
            show_validation_here.setText("Please write Digits");
        }
    }//GEN-LAST:event_t9KeyPressed

    private void firstTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstTimeActionPerformed

    /**:

     * @param args the command line argumentseyEvent evt) {                              
        // TODO add your handling code here:
    }                             

    /**
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> firstTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondTime;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
