/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Convertor;

import javax.swing.JFrame;

/**
 *
 * @author MEMONS
 */
public class Unit_Converter extends javax.swing.JFrame {

    /**
     * Creates new form Unit_Converter
     */
    public Unit_Converter() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UnitConvertor = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        TO = new javax.swing.JLabel();
        firstUnit = new javax.swing.JComboBox<>();
        secondUnit = new javax.swing.JComboBox<>();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.desktop);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));
        jPanel1.setLayout(null);

        UnitConvertor.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        UnitConvertor.setForeground(new java.awt.Color(255, 255, 255));
        UnitConvertor.setText("Temperature Converter");
        jPanel1.add(UnitConvertor);
        UnitConvertor.setBounds(450, 50, 540, 60);

        from.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        from.setForeground(new java.awt.Color(204, 204, 204));
        from.setText("FROM");
        jPanel1.add(from);
        from.setBounds(420, 130, 60, 22);

        TO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TO.setForeground(new java.awt.Color(204, 204, 204));
        TO.setText("TO");
        jPanel1.add(TO);
        TO.setBounds(760, 130, 40, 22);

        firstUnit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one ", "Celsius", "Kelvin", "Fehrenheit" }));
        jPanel1.add(firstUnit);
        firstUnit.setBounds(410, 160, 150, 30);

        secondUnit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one ", "Celsius", "Kelvin", "Fehrenheit", " " }));
        jPanel1.add(secondUnit);
        secondUnit.setBounds(750, 160, 144, 30);

        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        jPanel1.add(t3);
        t3.setBounds(410, 200, 180, 50);

        t4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(750, 200, 190, 50);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert Unit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 310, 180, 50);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 310, 130, 50);

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(810, 310, 130, 50);

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Traditional Arabic", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 390, 200, 60);

        show_validation_here.setForeground(new java.awt.Color(255, 0, 51));
        show_validation_here.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                show_validation_hereKeyPressed(evt);
            }
        });
        jPanel1.add(show_validation_here);
        show_validation_here.setBounds(410, 250, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        firstUnit.setSelectedIndex(0);
        secondUnit.setSelectedIndex(0);
        t3.setText(null);
        t4.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          BUtton home = new BUtton();
         home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String box1=(String)firstUnit.getSelectedItem();
        String box2=(String)secondUnit.getSelectedItem();
        if(box1.equals("Celsius") && box2.equals("Fahrenheit"))
       {
           double c = Double.parseDouble(t3.getText());
           double f = (double)(c * 1.8 + 32);
           t4.setText(String.valueOf(f));
       }
       else if(box1.equals("Celsius") && box2.equals("Kelvin"))
       {
           double c = Double.parseDouble(t3.getText());
           double k = (double)(c + 273.15 );
           t4.setText(String.valueOf(k));
       }
         else if(box1.equals("Celsius") && box2.equals("Celsius"))
       {
           double c = Double.parseDouble(t3.getText());
         
           t4.setText(String.valueOf(c));
       }
       if(box1.equals("Fahrenheit") && box2.equals("Celsius"))
       {
           double f = Double.parseDouble(t3.getText());
           
           double c = (double)((f - 32)*5/9);
           
           t4.setText(String.valueOf(c));
       }
       else if(box1.equals("Fahrenheit") && box2.equals("Kelvin"))
       {
           double f = Double.parseDouble(t3.getText());
           
           double k = (double)((f - 32)*5/9 + 273.15);
           
           t4.setText(String.valueOf(k));
       }
       else if(box1.equals("Fahrenheit") && box2.equals("Fahrenheit"))
       {
           double f = Double.parseDouble(t3.getText());
         
           t4.setText(String.valueOf(f));
       }
       if(box1.equals("Kelvin") && box2.equals("Celsius"))
       {
           double k = Double.parseDouble(t3.getText());
           
           double c = (double)(0 - 273.15);
           
           t4.setText(String.valueOf(c));
       }
       else if(box1.equals("Kelvin") && box2.equals("Fahrenheit"))
       {
           double k = Double.parseDouble(t3.getText());
           
           double f = (double)(0 - 273.15) * 9/5 +32;
           
           t4.setText(String.valueOf(f));
       }
       else if(box1.equals("Kelvin") && box2.equals("Kelvin"))
       {
           double k = Double.parseDouble(t3.getText());
         
           t4.setText(String.valueOf(k));
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void show_validation_hereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_show_validation_hereKeyPressed
         
    }//GEN-LAST:event_show_validation_hereKeyPressed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        t4.setEditable(false);
    }//GEN-LAST:event_t4ActionPerformed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
         try{
            int i=Integer.parseInt(t3.getText());
            show_validation_here.setText("");
        }
        catch(NumberFormatException e){
            show_validation_here.setText("Please write Digits");
        }
    }//GEN-LAST:event_t3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unit_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unit_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unit_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unit_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unit_Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TO;
    private javax.swing.JLabel UnitConvertor;
    private javax.swing.JComboBox<String> firstUnit;
    private javax.swing.JLabel from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> secondUnit;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
